### ISSUE TITLE
Green login mask

### ISSUE THREAD

**Issue by Stuii98** [NlightN22/sogo-dark-red#1]
hi 
first of all, thank you for that amazing theme!. 
i just wanted to share with you an issue i am facing with... 
after i successfully installed your theme, i noticed the login page is kinda buggy. Half site working fine the other dont. 
i just follwed your install guide and was facing to this (Cache cleared) 
here some screenshots 

path: /opt/mailcow/data/conf/sogo/

custom-favicon.ico
custom-sogo.js
custom-theme.css. <- your theme. Anything else to do here ? 
custom-theme.js
plist_ldap
sieve.creds
sogo.conf
sogo-full.svg

![Bildschirmfoto 2024-01-01 um 23 01 26](https://github.com/NlightN22/sogo-dark-red/assets/155396994/4e1ad5cf-9bbb-44f4-bd1a-949dec20a9aa)
![Bildschirmfoto 2024-01-01 um 23 11 28](https://github.com/NlightN22/sogo-dark-red/assets/155396994/2962a6c4-8fe4-4909-9ac6-8c2a1c24766f)

**Comment by NlightN22** [comment]
Hi! I updated the login screen.
![image](https://github.com/NlightN22/sogo-dark-red/assets/111307382/f4d69637-003a-421f-b8a6-d0f9a0c35ce2)
Download updated version of `custom-theme.css` and restart sogo `docker compose restart memcached-mailcow sogo-mailcow`

If you want to change logo or any other image on sogo you can change files at sogo container. Images path at container is -`/usr/lib/GNUstep/SOGo/WebServerResources/img/`.
You can see this by command `docker exec -it $(docker ps -f name=sogo-mailcow -q) ls /usr/lib/GNUstep/SOGo/WebServerResources/img/`
Any of changes you can do by create|modify docker-compose.override.yml. My example:
``` yml
version: '2.1'

services:
  sogo-mailcow:
    volumes:
      - ./data/conf/sogo/custom-theme.css:/usr/lib/GNUstep/SOGo/WebServerResources/css/theme-default.css:z
      - ./data/conf/sogo/logo-color.svg:/usr/lib/GNUstep/SOGo/WebServerResources/img/sogo-full.svg:z
```
